version: "3"

services:
  app:
    container-name: devnology-api
    build: .
    command: npm start
    ports:
      - "8082:3333"
    volume:
      - .:/usr/app

  postgres:
    container-name: devnology-db
    image: postgres-alpine
    environment:
      POSTGRES_USER: dev8
      POSTGRES_PASSWORD: dev8123
      POSRGRES_DB: devnology
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"
