version: "3"

services:
  app:
    container_name: devnology-api
    build: .
    command: node server.js
    ports:
      - "8082:3333"
    volumes:
      - .:/usr/app

  db:
    container_name: devnology-db
    image: postgres:13.9-alpine
    environment:
      POSTGRES_USER: dev8
      POSTGRES_PASSWORD: dev8123
      POSRGRES_DB: devnology
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"
